"""add updated_at to users

Revision ID: 4f5c1873669b
Revises: d29ff6cf90b3
Create Date: 2026-09-01 09:54:34.091010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5c1873669b'
down_revision: Union[str, Sequence[str], None] = 'd29ff6cf90b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
